import type { ResearchSeed } from "./types.js";

const docs = (url: string, extra?: string) => (extra ? [url, extra] : [url]);

export const researchSeeds: Record<string, ResearchSeed> = {
  Salesforce: {
    oneLineDescription: "Enterprise CRM platform for accounts, leads, opportunities, service, and custom objects.",
    authMethods: ["OAuth2", "JWT bearer", "session token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Connected-app setup, org permissions, and production OAuth review add operational work.",
    evidenceUrls: docs("https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm", "https://help.salesforce.com/s/articleView?id=sf.connected_app_create_api_integration.htm&type=5"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  HubSpot: {
    oneLineDescription: "CRM and marketing platform covering contacts, companies, deals, tickets, and automation.",
    authMethods: ["OAuth2", "private app token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Mostly scope design and rate-limit handling.",
    evidenceUrls: docs("https://developers.hubspot.com/docs/api/overview", "https://developers.hubspot.com/docs/api/private-apps"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Pipedrive: {
    oneLineDescription: "Sales CRM for leads, deals, pipelines, activities, and organizations.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Straightforward connector; main work is object coverage and pagination.",
    evidenceUrls: docs("https://developers.pipedrive.com/docs/api/v1", "https://pipedrive.readme.io/docs/marketplace-oauth-authorization"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Attio: {
    oneLineDescription: "Modern CRM workspace for companies, people, lists, records, and custom objects.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Need careful schema handling because records and lists are highly customizable.",
    evidenceUrls: docs("https://docs.attio.com/rest-api/overview", "https://docs.attio.com/rest-api/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Twenty: {
    oneLineDescription: "Open-source CRM with people, companies, opportunities, tasks, and customizable data.",
    authMethods: ["API key", "JWT", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Open-source deployments may differ, so connector should support instance URL configuration.",
    evidenceUrls: docs("https://twenty.com/developers", "https://github.com/twentyhq/twenty"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Podio: {
    oneLineDescription: "Work management and CRM-style app builder for organizations, apps, items, and tasks.",
    authMethods: ["OAuth2", "app token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Legacy app-token patterns and workspace permissions need careful handling.",
    evidenceUrls: docs("https://developers.podio.com/", "https://developers.podio.com/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Zoho CRM": {
    oneLineDescription: "CRM suite for leads, contacts, accounts, deals, activities, and automation.",
    authMethods: ["OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Regional domains and granular scopes must be modeled explicitly.",
    evidenceUrls: docs("https://www.zoho.com/crm/developer/docs/api/v7/", "https://www.zoho.com/accounts/protocol/oauth.html"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Close: {
    oneLineDescription: "Inside-sales CRM for leads, contacts, opportunities, calls, emails, and tasks.",
    authMethods: ["API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Main work is mapping activity objects and call/email event behavior.",
    evidenceUrls: docs("https://developer.close.com/", "https://developer.close.com/topics/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Copper: {
    oneLineDescription: "Google Workspace-native CRM for people, companies, opportunities, leads, and activities.",
    authMethods: ["API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API keys require a Copper account with sufficient plan/admin access.",
    evidenceUrls: docs("https://developer.copper.com/"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  DealCloud: {
    oneLineDescription: "Deal and relationship management platform for financial services workflows.",
    authMethods: ["OAuth2", "client credentials"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "broad_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Credentials and sandbox access appear tied to customer or partner access.",
    evidenceUrls: docs("https://api.docs.dealcloud.com/"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  Zendesk: {
    oneLineDescription: "Support platform for tickets, users, organizations, help center, chat, and routing.",
    authMethods: ["OAuth2", "API token", "Basic"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Large API surface needs staged coverage and permission-sensitive write actions.",
    evidenceUrls: docs("https://developer.zendesk.com/api-reference/", "https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/oauth-authentication-with-zendesk/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Intercom: {
    oneLineDescription: "Customer messaging and support platform for conversations, contacts, tickets, and help center.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Marketplace app review and scopes are the main operational steps.",
    evidenceUrls: docs("https://developers.intercom.com/docs/references/rest-api/api.intercom.io", "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Freshdesk: {
    oneLineDescription: "Helpdesk product for tickets, contacts, companies, agents, solutions, and automations.",
    authMethods: ["API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Domain-specific tenant URLs and API-key security need clean onboarding.",
    evidenceUrls: docs("https://developers.freshdesk.com/api/", "https://developers.freshworks.com/docs/app-sdk/v3.0/freshdesk/serverless-apps/oauth/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Front: {
    oneLineDescription: "Shared inbox and customer operations platform for conversations, contacts, channels, and teammates.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Conversation write actions need strong guardrails.",
    evidenceUrls: docs("https://dev.frontapp.com/reference/introduction", "https://dev.frontapp.com/docs/oauth"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Pylon: {
    oneLineDescription: "B2B customer support platform focused on Slack, Microsoft Teams, email, and customer portals.",
    authMethods: ["API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Public docs exist but credentials likely require a workspace/customer plan.",
    evidenceUrls: docs("https://docs.usepylon.com/"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  LiveAgent: {
    oneLineDescription: "Helpdesk and live-chat suite for tickets, chats, calls, customers, and knowledge base.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Instance URL and account-specific permissions must be captured.",
    evidenceUrls: docs("https://support.liveagent.com/965412-API"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Plain: {
    oneLineDescription: "Customer support platform with GraphQL APIs for customers, threads, issues, and events.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "GraphQL schema coverage and mutation guardrails are the main work.",
    evidenceUrls: docs("https://www.plain.com/docs/api-reference/graphql/overview", "https://www.plain.com/docs/api-reference/graphql/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Help Scout": {
    oneLineDescription: "Customer support platform for conversations, customers, mailboxes, docs, and teams.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Mailbox/team permissions should be surfaced clearly.",
    evidenceUrls: docs("https://developer.helpscout.com/mailbox-api/", "https://developer.helpscout.com/mailbox-api/overview/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Gorgias: {
    oneLineDescription: "Ecommerce helpdesk for tickets, customers, macros, rules, and Shopify-centric support workflows.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API access is tied to customer/admin accounts and ecommerce context.",
    evidenceUrls: docs("https://developers.gorgias.com/reference/introduction", "https://developers.gorgias.com/docs/oauth2"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Gladly: {
    oneLineDescription: "Enterprise customer-service platform for conversations, customers, tasks, and support channels.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "limited_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Developer access and production credentials appear enterprise/partner mediated.",
    evidenceUrls: docs("https://developer.gladly.com/rest/"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  Slack: {
    oneLineDescription: "Team messaging platform for channels, users, messages, files, workflows, and apps.",
    authMethods: ["OAuth2", "bot token", "user token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Marketplace review and granular scopes matter for public distribution.",
    evidenceUrls: docs("https://api.slack.com/web", "https://api.slack.com/authentication/oauth-v2"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Twilio: {
    oneLineDescription: "Communications API platform for SMS, voice, WhatsApp, verification, email, and conversations.",
    authMethods: ["Basic", "API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Phone-number setup, regional compliance, and spend limits are operational constraints.",
    evidenceUrls: docs("https://www.twilio.com/docs/usage/api", "https://www.twilio.com/docs/iam/api-keys"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Zoho Cliq": {
    oneLineDescription: "Team chat and collaboration platform in the Zoho suite.",
    authMethods: ["OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Zoho account region handling and scopes.",
    evidenceUrls: docs("https://www.zoho.com/cliq/help/restapi/v2/", "https://www.zoho.com/accounts/protocol/oauth.html"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Lark (Larksuite)": {
    oneLineDescription: "Collaboration suite for messaging, docs, calendar, approval, and workplace apps.",
    authMethods: ["OAuth2", "tenant token", "app access token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "App review, tenant installation, and regional Lark/Feishu differences.",
    evidenceUrls: docs("https://open.larksuite.com/document/home/index", "https://open.larksuite.com/document/server-docs/authentication-management/access-token/tenant_access_token_internal"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Pumble: {
    oneLineDescription: "Team chat app for channels, direct messages, users, and workspace communication.",
    authMethods: ["API token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API surface and developer access are narrower than Slack/Discord.",
    evidenceUrls: docs("https://pumble.com/help/integrations/api/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  Discord: {
    oneLineDescription: "Community chat platform with bots, guilds, channels, messages, and interactions.",
    authMethods: ["OAuth2", "bot token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Bot permissions and privileged intents must be handled explicitly.",
    evidenceUrls: docs("https://discord.com/developers/docs/intro", "https://discord.com/developers/docs/topics/oauth2"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Telegram: {
    oneLineDescription: "Messaging platform with Bot API for chats, messages, files, and updates.",
    authMethods: ["bot token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Bot-only API is strong but not equivalent to full user-account automation.",
    evidenceUrls: docs("https://core.telegram.org/bots/api", "https://core.telegram.org/bots/features"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "WhatsApp Business": {
    oneLineDescription: "Meta messaging API for business WhatsApp conversations, templates, and phone numbers.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Business verification, app review, phone-number setup, and template approval.",
    evidenceUrls: docs("https://developers.facebook.com/docs/whatsapp/cloud-api", "https://developers.facebook.com/docs/whatsapp/embedded-signup"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Aircall: {
    oneLineDescription: "Cloud phone system API for calls, contacts, numbers, users, teams, and webhooks.",
    authMethods: ["OAuth2", "API ID/key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Requires an Aircall account and admin-approved API/OAuth app access.",
    evidenceUrls: docs("https://developer.aircall.io/api-references/", "https://developer.aircall.io/api-references/#authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Vonage: {
    oneLineDescription: "Communications platform for SMS, voice, video, verification, and messaging APIs.",
    authMethods: ["API key/secret", "JWT", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Product-specific auth modes and telecom compliance need clear onboarding.",
    evidenceUrls: docs("https://developer.vonage.com/en/api", "https://developer.vonage.com/en/concepts/guides/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Google Ads": {
    oneLineDescription: "Advertising API for campaigns, customers, ads, assets, keywords, bidding, and reporting.",
    authMethods: ["OAuth2", "developer token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Developer token approval and account access are heavier than normal self-serve APIs.",
    evidenceUrls: docs("https://developers.google.com/google-ads/api/docs/start", "https://developers.google.com/google-ads/api/docs/oauth/overview"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Meta Ads": {
    oneLineDescription: "Marketing API for campaigns, ad sets, ads, creatives, audiences, and insights.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Business verification, app review, permissions, and ad-account access.",
    evidenceUrls: docs("https://developers.facebook.com/docs/marketing-apis/", "https://developers.facebook.com/docs/facebook-login/guides/access-tokens/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "LinkedIn Ads": {
    oneLineDescription: "LinkedIn Marketing API for ad accounts, campaigns, creatives, audiences, and analytics.",
    authMethods: ["OAuth2"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "broad_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Marketing API access commonly requires app review and product access approval.",
    evidenceUrls: docs("https://learn.microsoft.com/en-us/linkedin/marketing/", "https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  GoHighLevel: {
    oneLineDescription: "Agency CRM and marketing automation platform for locations, contacts, workflows, and calendars.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Agency/location model and OAuth scopes need careful data partitioning.",
    evidenceUrls: docs("https://highlevel.stoplight.io/docs/integrations/", "https://marketplace.gohighlevel.com/docs/oauth/Overview"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Mailchimp: {
    oneLineDescription: "Email marketing platform for audiences, campaigns, automations, templates, and reports.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Datacenter-specific API URLs and list permission guardrails.",
    evidenceUrls: docs("https://mailchimp.com/developer/marketing/api/", "https://mailchimp.com/developer/marketing/guides/access-user-data-oauth-2/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Klaviyo: {
    oneLineDescription: "Marketing automation platform for profiles, events, campaigns, flows, lists, and ecommerce messaging.",
    authMethods: ["API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Revisioned APIs and profile/event semantics need careful versioning.",
    evidenceUrls: docs("https://developers.klaviyo.com/en/reference/api_overview", "https://developers.klaviyo.com/en/docs/authenticate_"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "systeme.io": {
    oneLineDescription: "Funnel, email, course, and automation platform for online businesses.",
    authMethods: ["API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Public API coverage appears narrower than mature marketing platforms.",
    evidenceUrls: docs("https://developer.systeme.io/reference"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  Pinterest: {
    oneLineDescription: "Visual discovery and ads platform with pins, boards, catalogs, audiences, and ad reporting.",
    authMethods: ["OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "App review and advertising permissions can gate production use.",
    evidenceUrls: docs("https://developers.pinterest.com/docs/api/v5/", "https://developers.pinterest.com/docs/getting-started/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Threads (Meta)": {
    oneLineDescription: "Meta social platform API for Threads publishing, replies, insights, and profiles.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Newer API surface, Meta app review, and content permission constraints.",
    evidenceUrls: docs("https://developers.facebook.com/docs/threads", "https://developers.facebook.com/docs/threads/get-started"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  SendGrid: {
    oneLineDescription: "Email API platform for transactional email, templates, contacts, suppression, and analytics.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Email-domain verification and sending compliance are operational setup items.",
    evidenceUrls: docs("https://www.twilio.com/docs/sendgrid/api-reference", "https://www.twilio.com/docs/sendgrid/for-developers/sending-email/api-getting-started"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Shopify: {
    oneLineDescription: "Commerce platform for stores, products, orders, customers, inventory, and fulfillment.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Public app review and protected customer data requirements for broad distribution.",
    evidenceUrls: docs("https://shopify.dev/docs/api", "https://shopify.dev/docs/apps/build/authentication-authorization"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  WooCommerce: {
    oneLineDescription: "WordPress commerce plugin exposing products, orders, customers, coupons, and reports.",
    authMethods: ["consumer key/secret", "Basic"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Self-hosted WordPress instances vary in URL, plugins, and permission setup.",
    evidenceUrls: docs("https://woocommerce.github.io/woocommerce-rest-api-docs/", "https://woocommerce.com/document/woocommerce-rest-api/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  BigCommerce: {
    oneLineDescription: "Commerce platform API for catalogs, carts, orders, customers, checkouts, and store operations.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "App marketplace review and store-hash based tenant routing.",
    evidenceUrls: docs("https://developer.bigcommerce.com/docs/rest-management", "https://developer.bigcommerce.com/docs/start/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Salesforce Commerce Cloud": {
    oneLineDescription: "Enterprise commerce platform for shoppers, products, baskets, orders, and storefront APIs.",
    authMethods: ["OAuth2", "client credentials"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Sandbox/customer org access is the limiting operational dependency.",
    evidenceUrls: docs("https://developer.salesforce.com/docs/commerce/commerce-api/overview", "https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization.html"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Magento (Adobe Commerce)": {
    oneLineDescription: "Adobe Commerce/Magento APIs for catalog, cart, checkout, orders, customers, and admin operations.",
    authMethods: ["OAuth1", "integration token", "admin token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Self-hosted versions and store customizations create schema/version variance.",
    evidenceUrls: docs("https://developer.adobe.com/commerce/webapi/rest/", "https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Squarespace: {
    oneLineDescription: "Website and commerce platform with APIs for orders, inventory, products, and profiles.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API coverage is commerce-focused and requires eligible site/admin access.",
    evidenceUrls: docs("https://developers.squarespace.com/", "https://developers.squarespace.com/commerce-apis/overview"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Ecwid: {
    oneLineDescription: "Ecommerce platform for storefronts, products, orders, customers, and carts.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Store-specific access tokens and app installation flow.",
    evidenceUrls: docs("https://api-docs.ecwid.com/reference/rest-api", "https://api-docs.ecwid.com/reference/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Gumroad: {
    oneLineDescription: "Creator commerce platform for products, sales, subscribers, licenses, and offers.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API is useful but much narrower than full commerce platforms.",
    evidenceUrls: docs("https://gumroad.com/api"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  "Amazon Selling Partner": {
    oneLineDescription: "Amazon marketplace API for listings, orders, reports, feeds, inventory, and fulfillment.",
    authMethods: ["OAuth2", "Login with Amazon", "AWS Signature V4"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "broad_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Developer profile, app registration, role approval, and seller authorization are heavy gates.",
    evidenceUrls: docs("https://developer-docs.amazon.com/sp-api/docs", "https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  fanbasis: {
    oneLineDescription: "Creator monetization and fan engagement platform.",
    authMethods: ["unknown"],
    credentialAccess: "unclear",
    apiSurface: "private_or_no_public_api",
    buildability: "not_buildable_today",
    mainBlocker: "No clear public developer API or credential self-serve path found.",
    evidenceUrls: docs("https://www.fanbasis.com/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  DataForSEO: {
    oneLineDescription: "SEO and search-data API platform for SERP, keyword, backlinks, and competitor data.",
    authMethods: ["Basic"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Usage costs and task/result polling patterns must be managed.",
    evidenceUrls: docs("https://docs.dataforseo.com/v3/", "https://docs.dataforseo.com/v3/appendix-user-data/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "SE Ranking": {
    oneLineDescription: "SEO platform with APIs for rankings, projects, backlinks, competitors, and reports.",
    authMethods: ["API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Requires a paid account/API entitlement for practical use.",
    evidenceUrls: docs("https://seranking.com/api.html"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Ahrefs: {
    oneLineDescription: "SEO data platform for backlinks, keywords, pages, domains, and rank data.",
    authMethods: ["API token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API access is plan/credit gated and expensive enough to require commercial alignment.",
    evidenceUrls: docs("https://docs.ahrefs.com/docs/api/site-explorer/overview", "https://ahrefs.com/api"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  MrScraper: {
    oneLineDescription: "AI web-scraping API for extraction jobs, datasets, and scraping automation.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_now",
    mainBlocker: "Narrower scope than general app connectors but agent-callable extraction is straightforward.",
    evidenceUrls: docs("https://docs.mrscraper.com/"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Apify: {
    oneLineDescription: "Cloud platform for actors, web scraping, browser automation, datasets, and schedules.",
    authMethods: ["API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Actor-specific schemas vary, so generic tools need schema discovery.",
    evidenceUrls: docs("https://docs.apify.com/api/v2", "https://docs.apify.com/platform/integrations/api"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Firecrawl: {
    oneLineDescription: "Web crawling and scraping API for markdown extraction, maps, search, and batch jobs.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "mcp_available",
    buildability: "ready_now",
    mainBlocker: "Main work is credit/rate-limit handling and safe crawl constraints.",
    evidenceUrls: docs("https://docs.firecrawl.dev/introduction", "https://docs.firecrawl.dev/mcp-server"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  "Bright Data": {
    oneLineDescription: "Web data platform for proxies, scraping browser, datasets, and SERP/data collection.",
    authMethods: ["API token", "proxy credentials"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Paid account, compliance controls, and proxy/data product selection.",
    evidenceUrls: docs("https://docs.brightdata.com/api-reference/introduction", "https://docs.brightdata.com/general/account/api-token"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Sherlock: {
    oneLineDescription: "Open-source username search tool across social networks.",
    authMethods: ["none"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "It is a CLI/open-source project rather than a hosted authenticated API.",
    evidenceUrls: docs("https://github.com/sherlock-project/sherlock"),
    confidence: "high",
    mcpStatus: "not_applicable"
  },
  "Waterfall.io": {
    oneLineDescription: "Contact and company intelligence platform for enrichment and lead data.",
    authMethods: ["API key"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "private_or_no_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Developer docs and credentials appear gated behind sales/customer access.",
    evidenceUrls: docs("https://www.waterfall.io/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  Clay: {
    oneLineDescription: "AI sales and data enrichment workspace for lists, signals, workflows, and outreach data.",
    authMethods: ["API key", "webhook"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Public API coverage and credits are plan-dependent.",
    evidenceUrls: docs("https://docs.clay.com/en/articles/9672481-clay-api", "https://www.clay.com/"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  GitHub: {
    oneLineDescription: "Developer platform for repositories, issues, pull requests, Actions, packages, and code search.",
    authMethods: ["OAuth2", "GitHub App", "personal access token"],
    credentialAccess: "self_serve",
    apiSurface: "mcp_available",
    buildability: "ready_now",
    mainBlocker: "Choose between GitHub App and user OAuth based on tenant model.",
    evidenceUrls: docs("https://docs.github.com/en/rest", "https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/about-authentication-with-a-github-app"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  Vercel: {
    oneLineDescription: "Frontend cloud platform for projects, deployments, domains, environment variables, and teams.",
    authMethods: ["API token", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Team/project scoping and deployment safety controls.",
    evidenceUrls: docs("https://vercel.com/docs/rest-api", "https://vercel.com/docs/rest-api/reference/authentication"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  Netlify: {
    oneLineDescription: "Web hosting and deployment platform for sites, builds, deploys, DNS, and forms.",
    authMethods: ["OAuth2", "personal access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Site/team permissions and destructive deploy actions require confirmation flows.",
    evidenceUrls: docs("https://docs.netlify.com/api/get-started/", "https://open-api.netlify.com/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Cloudflare: {
    oneLineDescription: "Internet infrastructure platform for DNS, workers, accounts, zones, security, and storage.",
    authMethods: ["API token", "API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Large scope surface requires precise permission templates.",
    evidenceUrls: docs("https://developers.cloudflare.com/api/", "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Supabase: {
    oneLineDescription: "Postgres app platform with database, auth, storage, edge functions, and management APIs.",
    authMethods: ["API key", "JWT", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Differentiate project management APIs from generated database APIs.",
    evidenceUrls: docs("https://supabase.com/docs/reference/api", "https://supabase.com/docs/guides/api/api-keys"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Neo4j: {
    oneLineDescription: "Graph database platform with Aura management APIs and database driver access.",
    authMethods: ["API key", "Basic", "bearer token"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Agent toolkit should separate Aura admin APIs from graph query execution.",
    evidenceUrls: docs("https://neo4j.com/docs/aura/platform/api/overview/", "https://neo4j.com/docs/api/"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Snowflake: {
    oneLineDescription: "Cloud data platform for warehouses, databases, SQL, notebooks, stages, and governance.",
    authMethods: ["OAuth2", "key-pair JWT", "username/password"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Requires account/admin setup, warehouse access, and strong query safety.",
    evidenceUrls: docs("https://docs.snowflake.com/en/developer-guide/snowflake-rest-api/snowflake-rest-api", "https://docs.snowflake.com/en/developer-guide/sql-api/index"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "MongoDB Atlas": {
    oneLineDescription: "Managed MongoDB platform for clusters, projects, databases, users, backups, and monitoring.",
    authMethods: ["API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "IP access lists and project/org scoping need onboarding support.",
    evidenceUrls: docs("https://www.mongodb.com/docs/atlas/api/", "https://www.mongodb.com/docs/atlas/configure-api-access/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Datadog: {
    oneLineDescription: "Observability platform for metrics, logs, traces, monitors, incidents, dashboards, and security.",
    authMethods: ["API key", "application key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Site/region routing and high-risk monitor mutations need safeguards.",
    evidenceUrls: docs("https://docs.datadoghq.com/api/latest/", "https://docs.datadoghq.com/account_management/api-app-keys/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Sentry: {
    oneLineDescription: "Error monitoring platform for projects, issues, events, releases, alerts, and teams.",
    authMethods: ["OAuth2", "auth token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Organization/project scopes and destructive issue actions need guardrails.",
    evidenceUrls: docs("https://docs.sentry.io/api/", "https://docs.sentry.io/api/auth/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Notion: {
    oneLineDescription: "Workspace docs and database platform for pages, blocks, databases, comments, and users.",
    authMethods: ["OAuth2", "internal integration token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Database schemas and shared-page permissions shape what the agent can see.",
    evidenceUrls: docs("https://developers.notion.com/reference/intro", "https://developers.notion.com/docs/authorization"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  Airtable: {
    oneLineDescription: "No-code database platform for bases, tables, records, fields, automations, and interfaces.",
    authMethods: ["OAuth2", "personal access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Base-specific schemas require dynamic discovery.",
    evidenceUrls: docs("https://airtable.com/developers/web/api/introduction", "https://airtable.com/developers/web/guides/personal-access-tokens"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Linear: {
    oneLineDescription: "Product development system for issues, projects, cycles, teams, documents, and comments.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "GraphQL schemas and workspace permissions are the main implementation details.",
    evidenceUrls: docs("https://developers.linear.app/docs/graphql/working-with-the-graphql-api", "https://developers.linear.app/docs/oauth/authentication"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  Jira: {
    oneLineDescription: "Atlassian issue and project tracker for issues, projects, boards, workflows, and users.",
    authMethods: ["OAuth2", "API token", "Basic"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Atlassian Cloud/site scoping and permission complexity.",
    evidenceUrls: docs("https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/", "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Asana: {
    oneLineDescription: "Work management platform for tasks, projects, portfolios, teams, goals, and comments.",
    authMethods: ["OAuth2", "personal access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Workspace/project scoping and mutation confirmation flows.",
    evidenceUrls: docs("https://developers.asana.com/reference/rest-api-reference", "https://developers.asana.com/docs/oauth"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Monday.com": {
    oneLineDescription: "Work OS for boards, items, columns, automations, docs, and workflow apps.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "GraphQL complexity and board-specific schemas.",
    evidenceUrls: docs("https://developer.monday.com/api-reference/docs", "https://developer.monday.com/apps/docs/oauth"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  ClickUp: {
    oneLineDescription: "Project management platform for workspaces, spaces, folders, lists, tasks, docs, and goals.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Hierarchy mapping and workspace permissions.",
    evidenceUrls: docs("https://clickup.com/api", "https://clickup.com/api/developer-portal/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Coda: {
    oneLineDescription: "Document and table platform for docs, tables, rows, formulas, packs, and automation.",
    authMethods: ["API token", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Doc/table schema discovery is required for high-quality agent tools.",
    evidenceUrls: docs("https://coda.io/developers/apis/v1", "https://coda.io/developers/apis/v1#section/Authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Smartsheet: {
    oneLineDescription: "Work management platform for sheets, rows, reports, dashboards, attachments, and workflows.",
    authMethods: ["OAuth2", "access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Sheet-specific column schemas and enterprise permissions.",
    evidenceUrls: docs("https://smartsheet.redoc.ly/", "https://developers.smartsheet.com/api/smartsheet/guides/basics/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Harvest: {
    oneLineDescription: "Time tracking and invoicing platform for time entries, projects, clients, users, and invoices.",
    authMethods: ["OAuth2", "personal access token"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Account ID routing and time-entry write safety.",
    evidenceUrls: docs("https://help.getharvest.com/api-v2/", "https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Stripe: {
    oneLineDescription: "Payments platform for customers, payment intents, subscriptions, invoices, products, and billing.",
    authMethods: ["API key", "OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Financial write actions need confirmations and idempotency.",
    evidenceUrls: docs("https://docs.stripe.com/api", "https://docs.stripe.com/keys"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Plaid: {
    oneLineDescription: "Financial data network for bank account linking, transactions, identity, assets, and income.",
    authMethods: ["client ID/secret", "OAuth2 through Link"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Sandbox is self-serve, but production access requires review and compliance approval.",
    evidenceUrls: docs("https://plaid.com/docs/", "https://plaid.com/docs/api/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Binance: {
    oneLineDescription: "Crypto exchange APIs for market data, trading, account state, wallets, and futures.",
    authMethods: ["API key", "HMAC signature"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Trading actions require strict guardrails, regional availability checks, and key permissions.",
    evidenceUrls: docs("https://binance-docs.github.io/apidocs/spot/en/", "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  "Paygent Connect": {
    oneLineDescription: "Payment connectivity product associated with NMI-powered payment processing.",
    authMethods: ["API key", "token"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "private_or_no_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Public API documentation and sandbox credentials are not clearly self-serve.",
    evidenceUrls: docs("https://www.nmi.com/developers/", "https://www.paygent.co.jp/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  iPayX: {
    oneLineDescription: "AI-oriented payments or financial workflow platform with published docs but limited public footprint.",
    authMethods: ["API key"],
    credentialAccess: "unclear",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Docs suggest an API, but credential access and production approval path need confirmation.",
    evidenceUrls: docs("https://ipayx.ai/docs"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  QuickBooks: {
    oneLineDescription: "Accounting platform for companies, customers, invoices, bills, payments, reports, and payroll-adjacent data.",
    authMethods: ["OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Sandbox/company selection and accounting object semantics.",
    evidenceUrls: docs("https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account", "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Xero: {
    oneLineDescription: "Accounting platform for contacts, invoices, bills, bank transactions, journals, and reports.",
    authMethods: ["OAuth2"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Tenant selection and accounting write confirmations.",
    evidenceUrls: docs("https://developer.xero.com/documentation/api/accounting/overview", "https://developer.xero.com/documentation/guides/oauth2/overview/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Brex: {
    oneLineDescription: "Corporate spend platform for cards, expenses, users, payments, vendors, and transactions.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Business account/admin access and financial data controls.",
    evidenceUrls: docs("https://developer.brex.com/openapi", "https://developer.brex.com/docs/authentication/"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Ramp: {
    oneLineDescription: "Corporate card and finance automation platform for expenses, reimbursements, bills, users, and vendors.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "broad_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Customer/admin access, app approval, and financial write-action controls.",
    evidenceUrls: docs("https://docs.ramp.com/developer-api/v1/overview/introduction", "https://docs.ramp.com/developer-api/v1/overview/authentication"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  PitchBook: {
    oneLineDescription: "Private-market research platform with company, investor, deal, and fund data.",
    authMethods: ["API key", "token"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "limited_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Research API access is enterprise/commercially gated.",
    evidenceUrls: docs("https://pitchbook.com/products/apis", "https://pitchbook.com/"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  NotebookLM: {
    oneLineDescription: "Google research and note-taking product; related Gemini APIs exist but NotebookLM itself lacks broad public API.",
    authMethods: ["Google OAuth2", "service account"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "private_or_no_public_api",
    buildability: "not_buildable_today",
    mainBlocker: "NotebookLM is not exposed as a general self-serve public API; Gemini APIs are adjacent, not equivalent.",
    evidenceUrls: docs("https://cloud.google.com/gemini/docs", "https://support.google.com/notebooklm/"),
    confidence: "medium",
    mcpStatus: "none_found"
  },
  "Otter AI": {
    oneLineDescription: "Meeting transcription and notes platform with AI summaries and collaboration features.",
    authMethods: ["OAuth2", "MCP auth"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "mcp_available",
    buildability: "ready_with_limits",
    mainBlocker: "MCP/server access appears to depend on account capabilities rather than a broad public REST API.",
    evidenceUrls: docs("https://help.otter.ai/hc/en-us", "https://help.otter.ai/hc/en-us/articles/36204186741783-Otter-MCP-Server"),
    confidence: "medium",
    mcpStatus: "official_or_vendor_mcp"
  },
  Fathom: {
    oneLineDescription: "AI meeting recorder and notes product for calls, summaries, action items, and syncs.",
    authMethods: ["OAuth2", "API token"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "limited_public_api",
    buildability: "needs_outreach",
    mainBlocker: "Broad public developer docs and self-serve credentials are not clearly available.",
    evidenceUrls: docs("https://fathom.video/", "https://fathom.video/integrations"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  Consensus: {
    oneLineDescription: "AI academic-search product for querying research papers and evidence.",
    authMethods: ["OAuth2"],
    credentialAccess: "partner_or_sales_gated",
    apiSurface: "private_or_no_public_api",
    buildability: "needs_outreach",
    mainBlocker: "OAuth/API access appears request-based rather than self-serve public docs.",
    evidenceUrls: docs("https://consensus.app/", "https://consensus.app/home/api/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  Reducto: {
    oneLineDescription: "Document parsing API for extracting structured data from PDFs and complex documents.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "broad_public_api",
    buildability: "ready_now",
    mainBlocker: "Main work is file handling, async processing, and cost controls.",
    evidenceUrls: docs("https://docs.reducto.ai/", "https://docs.reducto.ai/api-reference/introduction"),
    confidence: "high",
    mcpStatus: "community_mcp_possible"
  },
  Devin: {
    oneLineDescription: "AI software engineering agent with API and MCP surfaces for tasks and development workflows.",
    authMethods: ["API token", "MCP auth"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "mcp_available",
    buildability: "ready_with_limits",
    mainBlocker: "Requires customer account access and careful task-permission boundaries.",
    evidenceUrls: docs("https://docs.devin.ai/api-reference/overview", "https://docs.devin.ai/mcp/overview"),
    confidence: "high",
    mcpStatus: "official_or_vendor_mcp"
  },
  higgsfield: {
    oneLineDescription: "AI media/content creation suite with CLI-oriented workflows.",
    authMethods: ["API key", "CLI auth"],
    credentialAccess: "unclear",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "Public API and credential story appears CLI/product-led rather than mature connector docs.",
    evidenceUrls: docs("https://higgsfield.ai/cli", "https://higgsfield.ai/"),
    confidence: "low",
    mcpStatus: "none_found"
  },
  "Mermaid CLI": {
    oneLineDescription: "Open-source CLI for rendering Mermaid diagrams to images and PDFs.",
    authMethods: ["none"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_now",
    mainBlocker: "This is a local CLI tool, so the connector is process execution rather than SaaS auth.",
    evidenceUrls: docs("https://github.com/mermaid-js/mermaid-cli"),
    confidence: "high",
    mcpStatus: "not_applicable"
  },
  "YouTube Transcript": {
    oneLineDescription: "Transcript extraction API for YouTube video captions and text.",
    authMethods: ["API key"],
    credentialAccess: "self_serve",
    apiSurface: "limited_public_api",
    buildability: "ready_now",
    mainBlocker: "Narrow, single-purpose API with dependency on transcript availability.",
    evidenceUrls: docs("https://www.transcriptapi.com/docs"),
    confidence: "medium",
    mcpStatus: "community_mcp_possible"
  },
  Grain: {
    oneLineDescription: "Meeting recording, transcription, clips, and notes platform for customer calls.",
    authMethods: ["OAuth2", "API key"],
    credentialAccess: "paid_or_admin_gated",
    apiSurface: "limited_public_api",
    buildability: "ready_with_limits",
    mainBlocker: "API access and meeting data permissions depend on customer/admin plan.",
    evidenceUrls: docs("https://grain.com/", "https://grain.com/api"),
    confidence: "low",
    mcpStatus: "none_found"
  }
};
